### ISSUE TITLE
Stop running action on backport PRs

### ISSUE THREAD

**Issue by fridgepoet** [grafana/code-coverage#11]
also, it seems that we are running the action for backport PRs, we can skip that: https://github.com/grafana/grafana/pull/47650#issuecomment-1096983135

_Originally posted by @andresmgot in https://github.com/grafana/code-coverage/discussions/8#discussioncomment-2557524_

**Comment by fridgepoet** [comment]
I tried to skip that [here](https://github.com/grafana/grafana/blob/main/.github/workflows/cloud-data-sources-code-coverage.yml#L13), but looks like that wasn't correct..

**Comment by andresmgot** [comment]
likely it should be just one wildcard, not two `**`

**Comment by fridgepoet** [comment]
Oops, so with `**` it is expecting a `/` ?

**Comment by andresmgot** [comment]
> Oops, so with `**` it is expecting a `/` ?

correct
